swagger: "2.0"
info:
  description: "Micro-serviço da base C"
  version: "1.0.0"
  title: "Swagger - Micro-serviço - base C"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "paulorfreitasjr@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "desafio.swagger.io"
basePath: "/v1"
tags:
- name: "rastreio"
  description: "Rastreio de eventos de crédito"
schemes:
- "https"
- "http"
paths:
  /rastreio/ultimaConsulta:
    get:
      tags:
      - "rastreio"
      summary: "Retorna os dados a respeito da ultima consulta do CPF em um Bureau de crédito"
      produces:
      - "application/json"
      parameters:
      - name: "cpf"
        in: "query"
        description: "CPF para consulta"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          # schema:
          #   type: "object"
          #   items:
          #     $ref: '#/definitions/ScoreCredito'
        400:
          description: "Invalid cpf value"
        401:
          description: "Unauthorized"
      security:
      - Bearer: []
  /rastreio/financa/movimentacoes:
    get:
      tags:
      - "rastreio"
      summary: "Retorna os dados de movimentação financeira"
      produces:
      - "application/json"
      parameters:
      - name: "cpf"
        in: "query"
        description: "CPF para consulta"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          # schema:
          #   type: "object"
          #   items:
          #     $ref: '#/definitions/ScoreCredito'
        400:
          description: "Invalid cpf value"
        401:
          description: "Unauthorized"
      security:
      - Bearer: []
  /rastreio/cartaocredito/compra/ultima:
    get:
      tags:
      - "rastreio"
      summary: "Retorna os dados da ultima compra no cartão de crédito vinculado ao CPF"
      produces:
      - "application/json"
      parameters:
      - name: "cpf"
        in: "query"
        description: "CPF para consulta"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          # schema:
          #   type: "object"
          #   items:
          #     $ref: '#/definitions/ScoreCredito'
        400:
          description: "Invalid cpf value"
        401:
          description: "Unauthorized"
      security:
      - Bearer: []
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"